### ISSUE TITLE
[JOSS] add contribution guidelines

### ISSUE THREAD

**Issue by faroit** [bootphon/pygamma-agreement#18]
The [JOSS review](https://github.com/openjournals/joss-reviews/issues/2989) criteria asks for "clear guidelines for third-parties wishing to"

* Contribute to the software
* Report issues or problems with the software
* Seek support

ideally, add this to a `contributing.md`

**Comment by hadware** [comment]
Thanks for that suggestion!

I added a CONTRIBUTING file to the repo, i hope it fits the bill. Do tell me if something isn't right.

**Comment by faroit** [comment]
looks great!
