### ISSUE TITLE
`Continuum.merge()` does not add annotators with no annotated segments

### ISSUE THREAD

**Issue by valentinoli** [bootphon/pygamma-agreement#35]
```py
c1 = Continuum()
c1.add_annotator('Annotator1')

c2 = Continuum()
c2.add('Annotator2', Segment(1, 2))

c2.merge(c1, in_place=True)

print(c2.annotators)
```

I expected the Annotator1 without any annotated segments to be added when merging the continuums.

If I change the second line to

`c1.add('Annotator1', Segment(0, 1))` then continuum `c2` includes Annotator1

**Comment by hadware** [comment]
Hey, thanks for the issue and the PR. I merged it an uploaded a new version of the package. Tell be if that fixes things :)

**Comment by valentinoli** [comment]
Thanks! But now two continuums are equal even though the set of annotators is different.

```py
c1 = Continuum()
c1.add_annotator('Annotator1')

c2 = Continuum()
c2.add('Annotator2', Segment(1, 2))

c2.merge(c1, in_place=True)

# that's fine
assert len(c1.annotators) == len(c2.annotators) - 1

# create new continuum the same as c2 but without Annotator1
c3 = Continuum()
c3.add('Annotator2', Segment(1, 2))

# they should not be equal, but they are
assert c2 == c3

assert len(c2.annotators) != len(c3.annotators)
```

**Comment by hadware** [comment]
I bumped the version number and included your fixes if you want to upgrade :)

Thanks again for your help!
