### ISSUE TITLE
Installation doesn't work as documented

### ISSUE THREAD

**Issue by TiMauzi** [bootphon/pygamma-agreement#45]
Downloading the package using `pip install pygamma-agreement` doesn't work properly, since you can't then import the file using `import pygamma_agreement`. Tried it on different hardware and operating systems, seems to be a problem with the package, though...

**Comment by hadware** [comment]
All right, it should be fixed by now. I added a workflow to make sure that this doesn't happen again. 

Thanks again for reporting this.
