### ISSUE TITLE
Change optimizer to MIP

### ISSUE THREAD

**Issue by hadware** [bootphon/pygamma-agreement#7]
From [this issue](https://github.com/cvxgrp/cvxpy/issues/1112) it seems that the solver we're currently using is not optimal (nor does it give correct results). Maybe we should consider switching to https://docs.python-mip.com/en/latest/quickstart.html .

**Comment by leopold0favre** [comment]
`python-mip` being unreliable for solving successive mixed integer problems in its current state due to definition time, we chose to keep using `CVXPY`, this time with the `CBC` solver (the one used by `python-mip`) to address precision problems.
